#!/usr/bin/env node
// Leak check: make sure notes do not reproduce the
// protected question bank / worked solutions.
//
// Compares text against the salted hashes in scripts/leak/fingerprints.v1.json.gz
// (generated by paper2db/scripts/leak_fingerprints.py). Levels:
//
//   L1    verbatim stem: >= 2 of an item's 8-grams appear (a pasted stem).
//   L2.1  numeric overlap: one block holds >= 50% of an item's numset (warning).
//   L2.2  numeric reword: one block holds the item's whole numset (fail), which
//         catches a stem reworded with the same numbers.
//   L3    verbatim worked solution / marking: >= 2 of an item's answer 8-grams.
//   L4    item id cited (e.g. PHY15013101) on a page that is not a deck.
//
// Baseline: the notes already embed some bank items on purpose (worked examples,
// practice checks). Those existing findings are pinned in scripts/leak/baseline.json
// as "LEVEL|path|item" keys and do not fail; anything not in the baseline does.
// Regenerate it with --update-baseline only when a new embed is intentional.
//
// Deck exemptions: pages under notes/qb/ and notes/dse/ (the item bank and past
// paper decks), `_source/` and `_local/` trees, and any page that declares
// <meta name="leak-check" content="deck">.
//
// normalize/tokens/numset MUST stay equivalent to leak_fingerprints.py.
//
// Usage: node paper2notes/scripts/leak-check.mjs [--verbose]
//          [--update-baseline] [file...]
//   no files: scans every non-exempt HTML under notes/ against the baseline.
//   explicit HTML files are checked with no baseline.

import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const paper2notesRoot = resolve(__dirname, "..");
const notesDir = join(paper2notesRoot, "notes");
export const DEFAULT_FINGERPRINTS = join(__dirname, "leak", "fingerprints.v1.json.gz");

export const DEFAULT_BASELINE = join(__dirname, "leak", "baseline.json");
const SCHEMA = "paper2everything.leak-fingerprints.v1";
const MIN_GRAM_HITS = 2;
const PARTIAL_NUMSET = 0.5;
const EXEMPT_DIRS = ["qb", "dse"]; // under notes/
const EXEMPT_SEGMENTS = new Set(["_source", "_local", "node_modules"]);

// ---- normalisation (mirror of leak_fingerprints.py) -------------------------

const TOKEN_RE = /[0-9a-z]+(?:\.[0-9]+)?/g;
const PLACEHOLDER_RE = /\[(?:fig|eq|tbl):\d+\]/g;
const THOUSANDS_RE = /(?<=[0-9]),(?=[0-9]{3})/g;
const NUMBER_RE = /^[0-9]+(?:\.[0-9]+)?$/;

export function normalize(text) {
  return text.normalize("NFKC").toLowerCase().replace(PLACEHOLDER_RE, " ").replace(THOUSANDS_RE, "");
}

export function tokens(text) {
  return normalize(text).match(TOKEN_RE) ?? [];
}

function canonicalNumber(tok) {
  if (tok.includes(".")) return tok.replace(/0+$/, "").replace(/\.$/, "");
  return tok.replace(/^0+/, "") || "0";
}

export function numset(toks) {
  const found = new Set();
  for (const tok of toks) {
    if (NUMBER_RE.test(tok) && tok.length >= 2) found.add(canonicalNumber(tok));
  }
  return found;
}

// ---- fingerprints -----------------------------------------------------------

export function loadFingerprints() {
  const fp = JSON.parse(gunzipSync(readFileSync(DEFAULT_FINGERPRINTS)).toString("utf8"));
  if (fp.schema !== SCHEMA) throw new Error(`${DEFAULT_FINGERPRINTS}: unexpected schema ${fp.schema}`);
  const digest = (value, hexLen) =>
    createHash("sha256").update(`${fp.salt}\u0000${value}`).digest("hex").slice(0, hexLen);
  const gramIndex = new Map(); // hash -> [item index]
  const wordIndex = new Map();
  fp.items.forEach((item, idx) => {
    for (const [list, index] of [[item.g, gramIndex], [item.w, wordIndex]]) {
      for (const h of list) {
        const hit = index.get(h);
        if (hit) hit.push(idx);
        else index.set(h, [idx]);
      }
    }
  });
  const numSets = fp.items.map((item) => new Set(item.nums));
  return {
    ...fp,
    gramIndex,
    wordIndex,
    numSets,
    gramHash: (toks, i) => digest(toks.slice(i, i + fp.ngram).join(" "), fp.gram_hex),
    numHash: (n) => digest(n, fp.num_hex),
    idPatterns: fp.items.map((item) => new RegExp(`(?<![A-Za-z0-9])${escapeRe(item.id)}(?![A-Za-z0-9])`, "i")),
  };
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---- text extraction --------------------------------------------------------

const BLOCK_TAGS = "address|article|aside|blockquote|br|dd|details|div|dl|dt|figcaption|figure|footer|h[1-6]|header|hr|li|main|nav|ol|p|pre|section|summary|table|td|th|tr|ul";
const ENTITIES = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ", deg: "°", times: "×", minus: "−", middot: "·" };

function decodeEntities(s) {
  return s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, e) => {
    if (e[0] === "#") {
      const code = e[1].toLowerCase() === "x" ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(code) && code <= 0x10ffff ? String.fromCodePoint(code) : m;
    }
    return ENTITIES[e.toLowerCase()] ?? m;
  });
}

/** Visible text of an HTML document as an array of blocks. */
export function htmlBlocks(html) {
  const stripped = html
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<head\b[\s\S]*?<\/head>/gi, " ")
    .replace(/<(script|style|noscript|template)\b[\s\S]*?<\/\1>/gi, " ")
    .replace(new RegExp(`</?(?:${BLOCK_TAGS})\\b[^>]*>`, "gi"), "\n")
    .replace(/<[^>]*>/g, " ");
  return decodeEntities(stripped)
    .split("\n")
    .map((b) => b.trim())
    .filter(Boolean);
}

export function isDeckPage(html) {
  return /<meta\b[^>]*\bname\s*=\s*["']leak-check["'][^>]*\bcontent\s*=\s*["']deck["']/i.test(html) ||
    /<meta\b[^>]*\bcontent\s*=\s*["']deck["'][^>]*\bname\s*=\s*["']leak-check["']/i.test(html);
}

function isExemptPath(file) {
  const rel = relative(notesDir, resolve(file)).split(/[\\/]/);
  if (rel[0] === ".." ) return false;
  if (rel.some((seg) => EXEMPT_SEGMENTS.has(seg))) return true;
  return EXEMPT_DIRS.includes(rel[0]);
}

// ---- checks -----------------------------------------------------------------

/**
 * Check a list of text blocks.
 * Returns findings [{level, item, detail, severity}].
 */
export function checkBlocks(blocks, fp) {
  const findings = [];
  const add = (level, item, detail, severity = "error") => findings.push({ level, item, detail, severity });

  const text = blocks.join("\n");
  const toks = tokens(text);

  // L1 / L3: 8-gram hits over the whole document.
  const gramHits = new Map();
  const wordHits = new Map();
  for (let i = 0; i + fp.ngram <= toks.length; i++) {
    const h = fp.gramHash(toks, i);
    for (const [index, hits] of [[fp.gramIndex, gramHits], [fp.wordIndex, wordHits]]) {
      for (const idx of index.get(h) ?? []) hits.set(idx, (hits.get(idx) ?? 0) + 1);
    }
  }
  for (const [idx, n] of gramHits) {
    if (n >= MIN_GRAM_HITS) add("L1", fp.items[idx].id, `${n} verbatim 8-grams of the question text`);
  }
  for (const [idx, n] of wordHits) {
    if (n >= MIN_GRAM_HITS) add("L3", fp.items[idx].id, `${n} verbatim 8-grams of the worked solution`);
  }

  // L2: numeric set inside a single block.
  const l2 = new Map(); // idx -> best {ratio, size}
  for (const block of blocks) {
    const hashes = new Set([...numset(tokens(block))].map(fp.numHash));
    if (hashes.size < fp.min_numset) continue;
    fp.numSets.forEach((set, idx) => {
      if (set.size === 0) return;
      let shared = 0;
      for (const h of set) if (hashes.has(h)) shared++;
      const ratio = shared / set.size;
      if (ratio >= PARTIAL_NUMSET && ratio > (l2.get(idx)?.ratio ?? 0)) l2.set(idx, { ratio, shared, size: set.size });
    });
  }
  for (const [idx, { ratio, shared, size }] of l2) {
    if (ratio === 1) add("L2.2", fp.items[idx].id, `one block reproduces the item's full numeric set (${size} numbers)`);
    else if (size >= 4) add("L2.1", fp.items[idx].id, `one block holds ${shared}/${size} of the item's numbers`, "warn");
  }

  // L4: item id cited.
  fp.idPatterns.forEach((re, idx) => {
    if (re.test(text)) add("L4", fp.items[idx].id, "protected item id cited outside a deck");
  });

  return findings;
}

export function checkFile(file, fp) {
  if (!/\.html?$/i.test(file)) throw new Error(`leak-check: expected an HTML file: ${file}`);
  const raw = readFileSync(file, "utf8");
  if (isDeckPage(raw) || isExemptPath(file)) return [];
  return checkBlocks(htmlBlocks(raw), fp);
}

function walkHtml(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!EXEMPT_SEGMENTS.has(entry.name)) walkHtml(full, out);
    } else if (entry.isFile() && entry.name.endsWith(".html")) {
      out.push(full);
    }
  }
  return out;
}

function findingKey(f, file) {
  return `${f.level}|${relative(paper2notesRoot, file).split(sep).join("/")}|${f.item}`;
}

function loadBaseline(path) {
  return existsSync(path) ? new Set(JSON.parse(readFileSync(path, "utf8")).allowed) : new Set();
}

/**
 * Scan files (default: all notes HTML, filtered through the baseline).
 * Returns {scanned, errors, warnings, baselined, stale, keys}.
 */
export function runLeakCheck({ files, baseline = DEFAULT_BASELINE } = {}) {
  if (!existsSync(DEFAULT_FINGERPRINTS)) {
    return { scanned: 0, errors: [`leak fingerprints missing: ${relative(process.cwd(), DEFAULT_FINGERPRINTS)} (run paper2db/scripts/leak_fingerprints.py)`], warnings: [], baselined: 0, stale: [], keys: [] };
  }
  const fp = loadFingerprints();
  const explicit = Boolean(files?.length);
  const targets = explicit ? files : existsSync(notesDir) ? walkHtml(notesDir) : [];
  const allowed = explicit ? new Set() : loadBaseline(baseline);
  const errors = [];
  const warnings = [];
  const seen = new Set();
  const keys = [];
  let baselined = 0;
  for (const file of targets) {
    for (const f of checkFile(file, fp)) {
      const msg = `${f.level} ${relative(process.cwd(), file)}: item ${f.item}: ${f.detail}`;
      if (f.severity === "warn") {
        warnings.push(msg);
        continue;
      }
      const key = findingKey(f, file);
      keys.push(key);
      seen.add(key);
      if (allowed.has(key)) baselined++;
      else errors.push(msg);
    }
  }
  const stale = [...allowed].filter((k) => !seen.has(k));
  return { scanned: targets.length, errors, warnings, baselined, stale, keys };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  let verbose = false;
  let update = false;
  const files = [];
  for (const arg of args) {
    if (arg === "--verbose") verbose = true;
    else if (arg === "--update-baseline") update = true;
    else if (arg.startsWith("-")) throw new Error(`leak-check: unknown option: ${arg}`);
    else files.push(resolve(arg));
  }
  const result = runLeakCheck({ files, baseline: update ? join(__dirname, "leak", "__none__") : DEFAULT_BASELINE });
  if (update) {
    const allowed = [...new Set([...result.keys])].sort();
    writeFileSync(DEFAULT_BASELINE, `${JSON.stringify({ note: "Existing embeds pinned by leak-check.mjs; LEVEL|path|item.", allowed }, null, 2)}\n`);
    console.log(`leak-check: baseline updated (${allowed.length} findings)`);
    process.exit(0);
  }
  if (verbose) for (const w of result.warnings) console.warn(`warn: ${w}`);
  else if (result.warnings.length) console.warn(`leak-check: ${result.warnings.length} L2.1 warning(s) (use --verbose)`);
  if (result.stale.length) console.warn(`leak-check: ${result.stale.length} baseline entr${result.stale.length === 1 ? "y" : "ies"} no longer occur; run --update-baseline to prune`);
  if (result.errors.length > 0) {
    console.error(`leak-check: ${result.errors.length} leak(s) in ${result.scanned} file(s):\n`);
    for (const e of result.errors) console.error(`  - ${e}`);
    process.exit(1);
  }
  console.log(`leak-check: OK (${result.scanned} file(s), ${result.baselined} baselined)`);
}
