#!/usr/bin/env python3
"""Generate per-year `ans_starts.json` marking-scheme page maps for lq-answers.

Reads `paper/ans/<year>ans.pdf`, reuses the Section A / front-matter / Paper 2
detection and question-label finding from `preprocess_lq_answers.py`, and writes
`tests/reconstructed/lq/<year>/ans_starts.json`:

    {"source_pdf": "2024ans.pdf", "pdf_pages": 12,
     "section_b_pdf_pages": [1, 2, 3, 4, 5],
     "questions": {"1": [1, 2], "2": [3], ...}}

Pages are 1-based marking-scheme PDF pages; whole pages are cropped per question
(questions sharing a page share its crop). Every Section B page is owned by at
least one question, and the mapped question set must equal the year's LQ
inventory from `metadata/lq/llm_classifications.json` - otherwise the script
writes the candidate file but exits 1 so a human fixes it before tracking.

Usage:
  python scripts/build_ans_starts.py --years 2024
  python scripts/build_ans_starts.py --all
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import fitz

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import preprocess_lq_answers as pla  # noqa: E402

LQ_CLASSIFICATIONS = ROOT / "metadata" / "lq" / "llm_classifications.json"
RECON_LQ = ROOT / "tests" / "reconstructed" / "lq"
ANS_DIR = ROOT / "paper" / "ans"

DOC = (
    "Per-year marking-scheme page map for LQ answer crops (year -> question -> "
    "1-based pdf pages). Whole pages are cropped, upright as scanned. Questions "
    "sharing a page share its crop. Generated by scripts/build_ans_starts.py, "
    "verified against metadata/lq/llm_classifications.json."
)


def expected_questions(year: str) -> list[int]:
    data = json.loads(LQ_CLASSIFICATIONS.read_text(encoding="utf-8"))
    return sorted(
        int(key.split("-q", 1)[1]) for key in data if key.startswith(f"{year}-q")
    )


def discover_years(wanted: list[str] | None) -> list[tuple[Path, str]]:
    out: list[tuple[Path, str]] = []
    for path in sorted(ANS_DIR.glob("*ans.pdf")):
        year = path.name[: -len("ans.pdf")]
        if wanted and year not in wanted:
            continue
        out.append((path, year))
    return out


def collect_panels(
    source: Path, max_questions: int, scale: float
) -> tuple[list, list[tuple[int, float, float]], object, int, list[int]]:
    """Mirror process_answers panel collection; return panels, meta, open doc, rot, pdf pages."""
    doc = fitz.open(source)
    pages: list = []
    panel_meta: list[tuple[int, float, float]] = []
    section_b_started = False
    seen_section_a = False
    included_pdf_pages: list[int] = []
    doc_rot = pla.detect_document_rotation(doc, scale)
    if doc_rot:
        print(f"  using page rotation {doc_rot}")
    stopped = False
    for index in range(len(doc)):
        if stopped:
            break
        if section_b_started and pla.is_paper_2_pdf_text(doc[index]):
            print(f"  stop at Paper 2 page {index + 1}/{len(doc)} (pdf text)")
            break
        image = pla.apply_rotation(pla.render_page(doc[index], scale), doc_rot)
        if doc_rot == 0:
            image = pla.normalize_answer_orientation(image)
        if pla.is_paper_2_page(image) and section_b_started:
            print(f"  stop at Paper 2 page {index + 1}/{len(doc)}")
            break
        panels = pla.split_answer_panels(image)
        n_panels = len(panels)
        pdf_labels = pla.page_has_pdf_question_labels(doc[index], max_questions)
        for panel_i, panel in enumerate(panels):
            label = (
                f"page {index + 1}/{len(doc)}"
                if n_panels == 1
                else f"page {index + 1}/{len(doc)} {'LR'[panel_i]}"
            )
            if not section_b_started:
                if pla.is_section_a_keys(panel):
                    seen_section_a = True
                    print(f"  skip Section A {label}")
                    continue
                if pla.is_front_matter(panel) and not (
                    pdf_labels
                    and re.search(
                        r"(?m)^\s*\d{1,2}\.\s*\(",
                        doc[index].get_text("text")[:2000] or "",
                    )
                ):
                    print(f"  skip front-matter {label}")
                    continue
                if pla.looks_like_section_b(panel) or pdf_labels:
                    section_b_started = True
                elif seen_section_a:
                    section_b_started = True
                else:
                    print(f"  skip unmarked {label}")
                    continue
            else:
                if pla.is_paper_2_page(panel):
                    print(f"  stop at Paper 2 {label}")
                    stopped = True
                    break
                if pla.is_section_a_keys(panel):
                    print(f"  stop at late Section A {label}")
                    stopped = True
                    break
            pages.append(panel)
            panel_meta.append((index, panel_i / n_panels, (panel_i + 1) / n_panels))
            if index not in included_pdf_pages:
                included_pdf_pages.append(index)
    return pages, panel_meta, doc, doc_rot, included_pdf_pages


def detect_starts(
    pages: list,
    panel_meta: list[tuple[int, float, float]],
    doc: object,
    doc_rot: int,
    max_questions: int,
    scale: float,
) -> tuple[list[tuple[int, int, int]], list[int]]:
    """Return ((qn, panel_idx, y) ...) starts plus inferred question numbers."""
    candidates: list[tuple[int, int, int]] = []
    for page_index, image in enumerate(pages):
        pdf_i, x0_frac, x1_frac = panel_meta[page_index]
        pdf_hits: list[tuple[int, int]] = []
        if doc_rot == 0 and doc is not None:
            pdf_hits = pla.find_main_question_ys_pdf(
                doc[pdf_i],
                max_questions=max_questions,
                scale=scale,
                x0_frac=x0_frac,
                x1_frac=x1_frac,
            )
        ocr_hits = pla.find_main_question_ys(image, max_questions)
        merged: dict[int, int] = {qn: y for qn, y in ocr_hits}
        for qn, y in pdf_hits:
            merged[qn] = y
        for qn, y in merged.items():
            candidates.append((qn, page_index, int(y)))
    before = {qn for qn, _, _ in pla.longest_question_chain(candidates, max_questions)}
    starts = pla.longest_question_chain(candidates, max_questions)
    starts = pla.ensure_leading_q1(starts, pages)
    starts = pla.fill_single_gaps(starts, pages)
    inferred = sorted({qn for qn, _, _ in starts} - before)
    return starts, inferred


def assign_pages(
    starts: list[tuple[int, int, int]],
    panel_meta: list[tuple[int, float, float]],
    included_pdf_pages: list[int],
) -> dict[int, list[int]]:
    """Whole-PDF-page (1-based) ownership per question with full coverage."""
    ordered = sorted(starts, key=lambda t: (panel_meta[t[1]][0], t[2], t[0]))
    start_pdf = [panel_meta[panel_idx][0] for _, panel_idx, _ in ordered]
    last_pdf = max(included_pdf_pages)
    assignment: dict[int, list[int]] = {}
    for i, (qn, _, _) in enumerate(ordered):
        own = start_pdf[i]
        if i + 1 < len(ordered):
            nxt = start_pdf[i + 1]
            end = max(own, nxt - 1)
        else:
            end = last_pdf
        assignment[qn] = sorted(set(range(own + 1, end + 2)))
    return assignment


def build_year(pdf: Path, year: str, scale: float) -> int:
    expected = expected_questions(year)
    if not expected:
        print(f"  WARNING: no LQ classifications for {year}; skipping")
        return 1
    max_q = max(expected)
    print(f"Answers: {pdf.name} (expect Q{min(expected)}-Q{max_q}, {len(expected)})")
    pages, panel_meta, doc, doc_rot, included = collect_panels(pdf, max_q, scale)
    try:
        if not pages:
            print("  WARNING: no Section B pages found")
            return 1
        starts, inferred = detect_starts(pages, panel_meta, doc, doc_rot, max_q, scale)
        if not starts:
            print("  WARNING: no LQ answer labels found")
            return 1
        assignment = assign_pages(starts, panel_meta, included)
        if inferred:
            print(f"  inferred (review closely): Q{sorted(inferred)}")
        for qn in sorted(assignment):
            print(f"  Q{qn}: pdf pages {assignment[qn]}")
    finally:
        doc.close()
    with fitz.open(pdf) as probe:
        pdf_pages = len(probe)
    payload = {
        "_doc": DOC,
        "source_pdf": pdf.name,
        "pdf_pages": pdf_pages,
        "section_b_pdf_pages": sorted(p + 1 for p in included),
        "questions": {str(q): pages_ for q, pages_ in sorted(assignment.items())},
    }
    dest = RECON_LQ / year / "ans_starts.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {dest.relative_to(ROOT)}")
    missing = [q for q in expected if q not in assignment]
    extra = [q for q in assignment if q not in expected]
    if missing or extra:
        print(f"  MISMATCH vs classifications: missing={missing} extra={extra}")
        print("  Fix detection or hand-edit ans_starts.json before tracking.")
        return 1
    # Coverage: every Section B page owned by at least one question.
    owned = {p for pages_ in assignment.values() for p in pages_}
    uncovered = sorted(set(payload["section_b_pdf_pages"]) - owned)
    if uncovered:
        print(f"  MISMATCH: Section B pages without owner: {uncovered}")
        return 1
    print(f"  OK: Q{min(expected)}-Q{max_q} complete, all Section B pages covered")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--years", nargs="*", default=None)
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--scale", type=float, default=2.0)
    args = parser.parse_args()
    if not args.all and not args.years:
        parser.error("pass --years YYYY [..] or --all")
    wanted = None if args.all else args.years
    papers = discover_years(wanted)
    if not papers:
        print("No answer PDFs matched.")
        return 1
    failures = 0
    for pdf, year in papers:
        print(f"\n=== ans-starts: {year} ({pdf.name}) ===")
        failures += build_year(pdf, year, args.scale)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
