#!/usr/bin/env python3
"""Derive answer keys for years without marking-scheme PDFs (3/3 unanimous Muse key-maker).

Target years are discovered, not hard-coded: classification years with no
`paper/ans/<year>ans.pdf` (MC), intersected with years that have an LQ paper
(LQ, via `tests/reconstructed/lq/<year>/starts.json`). Today that is
2026/pp/sap for MC and 2026/pp for LQ (sap has no Paper 1B).

For each target question the script builds the key-maker input (tesseract OCR
of the question crop/stack), then calls the Muse key-maker three times with
different method hints. A
derived key is recorded only on 3/3 unanimous agreement (MC option letter; LQ
per-subpart final answers after normalisation). Anything else - dissent,
illegible transcription, transport errors - is recorded as non-unanimous with
no derived key, for human adjudication on the Lavish review board.

Output is the tracked `metadata/derived_keys.json`; re-runs are free and
idempotent (existing entries are kept unless `--force`). `verify` (used by the
`keys` pipeline stage) fails only on questions with no recorded attempt.

Key-maker backend is the `pi` CLI (same pattern as paper2notes/scripts/audit):
  pi -p --provider <PI_PROVIDER> --model <PI_MODEL> --no-tools ... --mode text <prompt>
Defaults: provider `opencode-go`, model `muse-spark-1.3-contributor`.

Usage:
  python scripts/derive_keys.py verify
  python scripts/derive_keys.py derive --years 2026 pp sap --workers 4
  python scripts/derive_keys.py derive --paper mc --limit 2 --force
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
MC_CLASSIFICATIONS = ROOT / "metadata" / "mc" / "llm_classifications.json"
LQ_CLASSIFICATIONS = ROOT / "metadata" / "lq" / "llm_classifications.json"
DERIVED_KEYS = ROOT / "metadata" / "derived_keys.json"

RUNS_REQUIRED = 3

MC_HINTS = (
    "Method: solve directly from first principles, then pick the option.",
    "Method: rule out each distractor in turn (name the error each makes), then pick.",
    "Method: check units, orders of magnitude and limiting cases first, then solve and pick.",
)
LQ_HINTS = (
    "Method: solve each subpart from first principles, showing the marking points.",
    "Method: work backwards from the physics principle each subpart tests, then solve forwards.",
    "Method: solve with explicit unit and limiting-case checks at each step.",
)

MC_PROMPT = """You are marking HKDSE Physics (Hong Kong Diploma of Secondary Education).
This question is classified under: {section}.

{method}

Question transcription (source: {input_kind}; OCR may contain minor errors - if it is too corrupt to solve, return {{"option": null, "illegible": true}}):

---
{question}
---

Reply with a single JSON object on one line, no other text:
{{"option": "A"|"B"|"C"|"D"|null, "reasoning": "<one or two lines>", "illegible": false}}
If several options look defensible, still return your single best option."""

LQ_PROMPT = """You are marking HKDSE Physics (Hong Kong Diploma of Secondary Education).
This question is classified under: {section}.

{method}

Question transcription (source: {input_kind}; OCR may contain minor errors - if it is too corrupt to solve, return {{"illegible": true}}):

---
{question}
---

Reply with a single JSON object, no other text:
{{"subparts": {{"<label as printed>": "<final answer with units for that subpart>"}}, "worked": "<concise worked solution covering the marking points>", "illegible": false}}
Give a final answer for EVERY subpart shown (use the printed labels). For explanation subparts the final answer is the key conclusion in one sentence."""

DOC = (
    "Derived answer keys for classification years with no marking-scheme PDF "
    "(see paper/ans/). Each key needs 3/3 unanimous Muse key-maker runs "
    "(provider/model recorded); non-unanimous questions carry no derived key "
    "and are adjudicated on the Lavish derived-keys review board. "
    "Generated by scripts/derive_keys.py; re-runs replay this file."
)


# --- targets ---


def mc_years() -> list[str]:
    entries = json.loads(MC_CLASSIFICATIONS.read_text(encoding="utf-8"))
    return sorted({str(e["Year"]) for e in entries})


def lq_years() -> list[str]:
    data = json.loads(LQ_CLASSIFICATIONS.read_text(encoding="utf-8"))
    return sorted({k.split("-q", 1)[0] for k in data})


def has_ans_pdf(year: str) -> bool:
    return (ROOT / "paper" / "ans" / f"{year}ans.pdf").is_file()


def has_lq_paper(year: str) -> bool:
    return (ROOT / "tests" / "reconstructed" / "lq" / year / "starts.json").is_file()


def target_years(paper: str) -> list[str]:
    if paper == "mc":
        return [y for y in mc_years() if not has_ans_pdf(y)]
    return [y for y in lq_years() if not has_ans_pdf(y) and has_lq_paper(y)]


def mc_questions(year: str) -> list[int]:
    entries = json.loads(MC_CLASSIFICATIONS.read_text(encoding="utf-8"))
    return sorted(int(e["Question"]) for e in entries if str(e["Year"]) == year)


def lq_questions(year: str) -> list[int]:
    data = json.loads(LQ_CLASSIFICATIONS.read_text(encoding="utf-8"))
    return sorted(int(k.split("-q", 1)[1]) for k in data if k.startswith(f"{year}-q"))


def section_title(paper: str, year: str, q: int) -> str:
    if paper == "mc":
        entries = json.loads(MC_CLASSIFICATIONS.read_text(encoding="utf-8"))
        for e in entries:
            if str(e["Year"]) == year and int(e["Question"]) == q:
                return f"section {e['sections'][0]} ({e.get('reason', '')[:120]})"
    else:
        data = json.loads(LQ_CLASSIFICATIONS.read_text(encoding="utf-8"))
        entry = data.get(f"{year}-q{q}")
        if entry:
            return f"section {entry['sections'][0]} ({entry.get('reason', '')[:120]})"
    return "unknown section"


# --- inputs ---


def ocr_image(path: Path, psm: str = "6") -> str:
    from PIL import Image

    with Image.open(path) as im:
        buf = io.BytesIO()
        im.convert("RGB").save(buf, format="PNG")
    result = subprocess.run(
        ["tesseract", "stdin", "stdout", "--psm", psm],
        input=buf.getvalue(),
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.stdout.decode("utf-8", errors="ignore")


def mc_crop(year: str, q: int) -> Path | None:
    path = ROOT / "tests" / "reconstructed" / "mc" / year / f"q{q}.png"
    return path if path.is_file() else None


def lq_stack(year: str, q: int) -> Path | None:
    path = ROOT / "tests" / "reconstructed" / "lq" / year / f"q{q}.png"
    return path if path.is_file() else None


def crop_source_for(paper: str, year: str, q: int) -> Path | None:
    return mc_crop(year, q) if paper == "mc" else lq_stack(year, q)


def question_input(paper: str, year: str, q: int) -> dict:
    if paper == "mc":
        crop = mc_crop(year, q)
        if crop is not None:
            text = ocr_image(crop).strip()
            return {
                "kind": "crop-ocr",
                "source": crop.relative_to(ROOT).as_posix(),
                "text": text,
            }
        raise SystemExit(
            f"No MC crop tests/reconstructed/mc/{year}/q{q}.png; "
            f"run ./pipeline --only mc-anchors,mc-split --years {year} first."
        )
    stack = lq_stack(year, q)
    if stack is not None:
        text = ocr_image(stack).strip()
        return {
            "kind": "stack-ocr",
            "source": stack.relative_to(ROOT).as_posix(),
            "text": text,
        }
    raise SystemExit(
        f"No LQ stack tests/reconstructed/lq/{year}/q{q}.png; "
        f"run ./pipeline --only lq-pages,lq-crops --years {year} first."
    )


def input_sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


# --- key-maker ---


def pi_command(
    prompt: str, provider: str, model: str, pi_bin: str, image: Path | None = None
) -> list[str]:
    cmd = [
        pi_bin,
        "-p",
        "--provider",
        provider,
        "--model",
        model,
        "--no-tools",
        "--no-extensions",
        "--no-skills",
        "--no-context-files",
        "--no-prompt-templates",
        "--no-themes",
        "--no-session",
        "--mode",
        "text",
    ]
    if image is not None:
        cmd.append(f"@{image}")
    cmd.append(prompt)
    return cmd


def run_key_maker(
    prompt: str,
    provider: str,
    model: str,
    pi_bin: str,
    timeout: int = 300,
    image: Path | None = None,
) -> dict:
    last_error = "no attempts"
    for attempt in (1, 2, 3):
        try:
            proc = subprocess.run(
                pi_command(prompt, provider, model, pi_bin, image),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout,
                check=False,
            )
        except subprocess.TimeoutExpired:
            last_error = f"timeout after {timeout}s"
            time.sleep(10 * attempt)
            continue
        if proc.returncode != 0:
            last_error = proc.stderr.decode("utf-8", errors="ignore")[-300:]
            time.sleep(10 * attempt)
            continue
        return {"ok": True, "output": proc.stdout.decode("utf-8", errors="ignore")}
    return {"ok": False, "error": last_error}


JSON_RE = re.compile(r"\{.*\}", re.S)


def parse_json_output(output: str) -> dict | None:
    match = JSON_RE.search(output or "")
    if not match:
        return None
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def parse_mc_run(output: str) -> dict:
    data = parse_json_output(output)
    if not data or data.get("illegible"):
        return {"option": None, "reasoning": (data or {}).get("reasoning", "")}
    option = str(data.get("option") or "").strip().upper()
    if option not in ("A", "B", "C", "D"):
        match = re.search(r"\b([A-D])\b", output)
        option = match.group(1) if match else None
    return {"option": option, "reasoning": str(data.get("reasoning", ""))[:500]}


def normalize_final(value: object) -> str:
    """Normalise an LQ subpart final answer for unanimity comparison.

    Case/whitespace-insensitive; numbers compare with tolerance so
    "2.10 m" and "2.1 m" agree, but differing units still disagree.
    """
    text = str(value or "").strip().lower()
    text = re.sub(r"\s+", " ", text).strip(" .,;:")
    match = re.fullmatch(
        r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*(.*)", text
    )
    if match:
        try:
            number = float(match.group(1))
        except ValueError:
            return text
        unit = re.sub(r"\s+", " ", match.group(2)).strip()
        return f"{number:.6g} {unit}".strip()
    return text


def parse_lq_run(output: str) -> dict:
    data = parse_json_output(output)
    if not data or data.get("illegible"):
        return {"subparts": {}, "worked": "", "illegible": True}
    subparts = data.get("subparts")
    if not isinstance(subparts, dict) or not subparts:
        return {"subparts": {}, "worked": "", "illegible": True}
    return {
        "subparts": {str(k): str(v) for k, v in subparts.items()},
        "worked": str(data.get("worked", ""))[:4000],
        "illegible": False,
    }


def mc_unanimous(runs: list[dict]) -> str | None:
    options = [r.get("option") for r in runs]
    if len(options) == RUNS_REQUIRED and all(o and o == options[0] for o in options):
        return options[0]
    return None


def lq_unanimous(runs: list[dict]) -> dict | None:
    if len(runs) != RUNS_REQUIRED or any(r.get("illegible") for r in runs):
        return None
    keys = [tuple(sorted(r["subparts"])) for r in runs]
    if any(k != keys[0] for k in keys):
        return None
    merged: dict[str, str] = {}
    for label in keys[0]:
        norms = [normalize_final(r["subparts"][label]) for r in runs]
        if any(n != norms[0] for n in norms):
            return None
        merged[label] = runs[0]["subparts"][label]
    return merged


# --- store ---


def blank_store() -> dict:
    return {"_doc": DOC, "key_maker": {}, "mc": {}, "lq": {}}


def load_store() -> dict:
    if not DERIVED_KEYS.is_file():
        return blank_store()
    data = json.loads(DERIVED_KEYS.read_text(encoding="utf-8"))
    data.setdefault("_doc", DOC)
    data.setdefault("key_maker", {})
    data.setdefault("mc", {})
    data.setdefault("lq", {})
    return data


def save_store(data: dict) -> None:
    DERIVED_KEYS.parent.mkdir(parents=True, exist_ok=True)
    DERIVED_KEYS.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def derive_one(
    paper: str,
    year: str,
    q: int,
    provider: str,
    model: str,
    pi_bin: str,
    with_images: bool = False,
) -> dict:
    try:
        question = question_input(paper, year, q)
    except SystemExit as exc:
        return {
            "unanimous": False,
            "error": str(exc),
            "runs": [],
            "key_maker": {"provider": provider, "model": model},
        }
    section = section_title(paper, year, q)
    kind_label = {
        "crop-ocr": "tesseract OCR of the question crop",
        "stack-ocr": "tesseract OCR of the whole-page question stack",
    }.get(question["kind"], question["kind"])
    image: Path | None = None
    if with_images:
        crop_path = crop_source_for(paper, year, q)
        if crop_path is not None:
            image = crop_path
            kind_label += " plus the attached question image (trust the image over the transcription)"
    entry: dict = {
        "input": {
            "kind": question["kind"] + ("+vision" if image is not None else ""),
            "source": question["source"],
            "sha": input_sha(question["text"]),
            "text": question["text"],
        },
        "key_maker": {"provider": provider, "model": model, "runs": RUNS_REQUIRED},
    }
    if paper == "mc":
        prompts = [
            MC_PROMPT.format(
                section=section,
                method=hint,
                input_kind=kind_label,
                question=question["text"],
            )
            for hint in MC_HINTS
        ]
        runs = []
        for prompt in prompts:
            result = run_key_maker(prompt, provider, model, pi_bin, image=image)
            if not result["ok"]:
                runs.append({"option": None, "error": result["error"]})
            else:
                runs.append(parse_mc_run(result["output"]))
        entry["runs"] = runs
        option = mc_unanimous(runs)
        entry["unanimous"] = option is not None
        entry["option"] = option
        return entry
    prompts = [
        LQ_PROMPT.format(
            section=section,
            method=hint,
            input_kind=kind_label,
            question=question["text"],
        )
        for hint in LQ_HINTS
    ]
    runs = []
    for prompt in prompts:
        result = run_key_maker(prompt, provider, model, pi_bin, image=image)
        if not result["ok"]:
            runs.append({"subparts": {}, "worked": "", "error": result["error"]})
        else:
            runs.append(parse_lq_run(result["output"]))
    entry["runs"] = runs
    finals = lq_unanimous(runs)
    entry["unanimous"] = finals is not None
    entry["final_answers"] = finals
    entry["worked"] = runs[0].get("worked", "") if finals is not None else ""
    return entry


def cmd_derive(args: argparse.Namespace) -> int:
    provider = args.provider or os.environ.get("PI_PROVIDER", "opencode-go")
    model = args.model or os.environ.get("PI_MODEL", "muse-spark-1.3-contributor")
    pi_bin = args.pi_bin or os.environ.get("PI_BIN", "pi")
    papers = ["mc", "lq"] if args.paper == "both" else [args.paper]
    store = load_store()
    store["key_maker"] = {
        "provider": provider,
        "model": model,
        "runs": RUNS_REQUIRED,
        "rule": "3/3 unanimous",
    }
    jobs: list[tuple[str, str, int]] = []
    for paper in papers:
        for year in target_years(paper):
            if args.years and year not in args.years:
                continue
            questions = mc_questions(year) if paper == "mc" else lq_questions(year)
            if args.questions:
                wanted = {int(x) for x in args.questions}
                questions = [q for q in questions if q in wanted]
            existing = store.get(paper, {}).get(year, {})
            for q in questions:
                if str(q) in existing and not args.force:
                    continue
                jobs.append((paper, year, q))
                if args.limit and len(jobs) >= args.limit:
                    break
            if args.limit and len(jobs) >= args.limit:
                break
    print(f"derive: {len(jobs)} questions via {provider}/{model} x{RUNS_REQUIRED}")
    if not jobs:
        print("nothing to do (all recorded; use --force to re-run)")
        return 0
    failures = 0
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        future_map = {
            pool.submit(
                derive_one, paper, year, q, provider, model, pi_bin, args.with_images
            ): (
                paper,
                year,
                q,
            )
            for paper, year, q in jobs
        }
        for future in as_completed(future_map):
            paper, year, q = future_map[future]
            try:
                entry = future.result()
            except Exception as exc:  # never lose the batch to one question
                entry = {"unanimous": False, "error": str(exc), "runs": []}
                failures += 1
            store.setdefault(paper, {}).setdefault(year, {})[str(q)] = entry
            verdict = "unanimous" if entry.get("unanimous") else "NON-UNANIMOUS"
            print(f"  {paper} {year} q{q}: {verdict}")
            save_store(store)
    unanimous = sum(
        1
        for paper in papers
        for year in store.get(paper, {})
        for e in store[paper][year].values()
        if e.get("unanimous")
    )
    print(f"recorded {unanimous} unanimous in {DERIVED_KEYS.relative_to(ROOT)}")
    return 1 if failures else 0


def cmd_verify(_args: argparse.Namespace) -> int:
    store = load_store()
    problems: list[str] = []
    non_unanimous: list[str] = []
    for paper in ("mc", "lq"):
        for year in target_years(paper):
            questions = mc_questions(year) if paper == "mc" else lq_questions(year)
            recorded = store.get(paper, {}).get(year, {})
            for q in questions:
                key = f"{paper} {year} q{q}"
                entry = recorded.get(str(q))
                if not entry:
                    problems.append(f"missing {key}")
                    continue
                if len(entry.get("runs", [])) != RUNS_REQUIRED:
                    problems.append(f"{key}: {len(entry.get('runs', []))} runs recorded")
                elif not entry.get("unanimous"):
                    non_unanimous.append(key)
    for line in problems:
        print(f"  ERROR {line}")
    for key in non_unanimous:
        print(f"  non-unanimous (no derived key): {key}")
    total = sum(
        len(store.get(p, {}).get(y, {}))
        for p in ("mc", "lq")
        for y in target_years(p)
    )
    print(f"verify: {total} recorded, {len(problems)} missing, {len(non_unanimous)} non-unanimous")
    return 1 if problems else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    verify_p = sub.add_parser("verify", help="fail unless every target has a recorded attempt")
    verify_p.set_defaults(func=cmd_verify)
    derive_p = sub.add_parser("derive", help="run the Muse key-maker for missing targets")
    derive_p.add_argument("--years", nargs="*", default=None)
    derive_p.add_argument("--paper", choices=("mc", "lq", "both"), default="both")
    derive_p.add_argument("--questions", nargs="*", default=None)
    derive_p.add_argument("--limit", type=int, default=None)
    derive_p.add_argument("--workers", type=int, default=4)
    derive_p.add_argument("--force", action="store_true")
    derive_p.add_argument(
        "--with-images",
        action="store_true",
        help="attach the question crop/stack image to each key-maker call",
    )
    derive_p.add_argument("--provider", default=None)
    derive_p.add_argument("--model", default=None)
    derive_p.add_argument("--pi-bin", default=None)
    derive_p.set_defaults(func=cmd_derive)
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
